[pytest]
addopts = -v --tb=short --tracing retain-on-failure --alluredir=allure-results --html=reports/report1.html
markers =
    smoke: Smoke tests - critical path verification
    regression: Regression tests - full coverage
    api: API tests
    ui: UI tests
testpaths = tests
